spring:
  datasource:
    url: jdbc:mysql://192.168.40.171:3306/springtest?characterEncoding=utf8
    username: root
    password: 080336
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    properties:
        hibernate:
             dialect: org.hibernate.dialect.MySQL5Dialect



